In [1]:
import numpy as np
from scipy import linalg

In [2]:
#A = np.mat([[2, 0, 1], [0, 1, 1], [1, 1, 0]])

u1 = np.mat([[0.70711],
           [-0.70711]])

In [3]:
E1 = u1 * u1.T
E1

matrix([[ 0.50000455, -0.50000455],
        [-0.50000455,  0.50000455]])

In [4]:
u2 = np.mat([[0.70711],
           [0.70711]])

In [5]:
E2 = u2 * u2.T
E2

matrix([[0.50000455, 0.50000455],
        [0.50000455, 0.50000455]])

In [6]:
A = 1 * E1 + 5 * E2
A

matrix([[3.00002731, 2.00001821],
        [2.00001821, 3.00002731]])

In [7]:
V1 = np.mat([[0.57735],
           [0.57735],
            [0.57735]])
V1

matrix([[0.57735],
        [0.57735],
        [0.57735]])

In [8]:
E1 = V1 * V1.T
E1

matrix([[0.33333302, 0.33333302, 0.33333302],
        [0.33333302, 0.33333302, 0.33333302],
        [0.33333302, 0.33333302, 0.33333302]])

In [9]:
V2 = np.mat([[0.66057],
           [0.08532],
            [-0.74590]])
V2

matrix([[ 0.66057],
        [ 0.08532],
        [-0.7459 ]])

In [10]:
E2 = V2 * V2.T
E2

matrix([[ 0.43635272,  0.05635983, -0.49271916],
        [ 0.05635983,  0.0072795 , -0.06364019],
        [-0.49271916, -0.06364019,  0.55636681]])

In [11]:
V3 = np.mat([[0.47991],
           [-0.81203],
            [0.33212]])
V3

matrix([[ 0.47991],
        [-0.81203],
        [ 0.33212]])

In [12]:
E3 = V3 * V3.T
E3

matrix([[ 0.23031361, -0.38970132,  0.15938771],
        [-0.38970132,  0.65939272, -0.2696914 ],
        [ 0.15938771, -0.2696914 ,  0.11030369]])

In [13]:
a1 = 1.4*E1
a1

matrix([[0.46666623, 0.46666623, 0.46666623],
        [0.46666623, 0.46666623, 0.46666623],
        [0.46666623, 0.46666623, 0.46666623]])

In [14]:
a2 = 0.8*E2
a2

matrix([[ 0.34908218,  0.04508787, -0.39417533],
        [ 0.04508787,  0.0058236 , -0.05091215],
        [-0.39417533, -0.05091215,  0.44509345]])

In [15]:
a3 = 0.8*E3
a3

matrix([[ 0.18425089, -0.31176105,  0.12751017],
        [-0.31176105,  0.52751418, -0.21575312],
        [ 0.12751017, -0.21575312,  0.08824296]])

In [16]:
A = a1 + a2 + a3
A

matrix([[0.9999993 , 0.19999304, 0.20000107],
        [0.19999304, 1.00000401, 0.20000096],
        [0.20000107, 0.20000096, 1.00000264]])