In [1]:
import numpy as np
from scipy import linalg

In [2]:
A = np.mat([[2, 0, 1],
           [0, 1, 1],
           [1, 1, 0]])

b = np.mat([[1],
           [0],
           [1]])

In [3]:
print(A, "\n")
print(b)

[[2 0 1]
 [0 1 1]
 [1 1 0]] 

[[1]
 [0]
 [1]]


In [4]:
# Problem 2.1
#a. Find inverse(A)
A_inverse = linalg.inv(A)
A_inverse

array([[ 0.33333333, -0.33333333,  0.33333333],
       [-0.33333333,  0.33333333,  0.66666667],
       [ 0.33333333,  0.66666667, -0.66666667]])

In [5]:
test = A * A_inverse
test

matrix([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [5.55111512e-17, 5.55111512e-17, 1.00000000e+00]])

In [6]:
# Problem 2.1
#b. Solve Ax = b using inverse(A)
x = A_inverse * b
print(x, "\n")
# proof 
proof = A * x
print(proof)

[[ 0.66666667]
 [ 0.33333333]
 [-0.33333333]] 

[[1.]
 [0.]
 [1.]]


In [7]:
np.linalg.matrix_rank(A)

3

In [8]:
# Problem 2.2
A = np.mat([[2,2,6],
           [-1,1,-1]])
print(A)
np.linalg.matrix_rank(A)

[[ 2  2  6]
 [-1  1 -1]]


2

In [9]:
# Problem 2.3 Generalized Inverse
A = np.mat([[2,2,6],
           [-1,1,-1]])
b = ([[1],
     [0]])
print("A is a 2X3 matrix equal to \n", A, "\n")
print("b is a 2X1 matrix equal to \n", b, "\n")

A is a 2X3 matrix equal to 
 [[ 2  2  6]
 [-1  1 -1]] 

b is a 2X1 matrix equal to 
 [[1], [0]] 



In [10]:
# Problem 2.3
#a. Find a generalized inverse(A)
A_inverse = linalg.pinv(A)
A_inverse

array([[ 1.70632820e-17, -3.33333333e-01],
       [ 1.25000000e-01,  5.83333333e-01],
       [ 1.25000000e-01, -8.33333333e-02]])

In [11]:
A_generalized1 = A.T*linalg.inv(A*A.T)
A_generalized1

matrix([[ 0.        , -0.33333333],
        [ 0.125     ,  0.58333333],
        [ 0.125     , -0.08333333]])

In [12]:
A_AT = A * A.T
print(A_AT)

[[44 -6]
 [-6  3]]


In [13]:
A_AT_inv = linalg.inv(A*A.T)
print(A_AT_inv)

[[0.03125    0.0625    ]
 [0.0625     0.45833333]]


In [14]:
A_generalized_inv = A.T * A_AT_inv
print(A_generalized_inv)

[[ 0.         -0.33333333]
 [ 0.125       0.58333333]
 [ 0.125      -0.08333333]]


In [15]:
b = np.mat([[1], 
            [0]])
x = A_generalized_inv * b
print(x)

[[0.   ]
 [0.125]
 [0.125]]


In [17]:
#2.4 Determinants
A = np.mat([[0, 1, 0],
           [2, 0, 1],
           [1, 2, 1]])
print(A)

[[0 1 0]
 [2 0 1]
 [1 2 1]]


In [18]:
det_A = linalg.det(A)
print(det_A)

-1.0


In [19]:
A_inv = linalg.inv(A)
print(A_inv)

[[ 2.  1. -1.]
 [ 1.  0.  0.]
 [-4. -1.  2.]]


In [21]:
print("rank(A) is: \n", np.linalg.matrix_rank(A), "\n")

rank(A) is: 
 3 



In [23]:
det_A_trans = linalg.det(A.T)
print(det_A_trans)

-1.0


In [24]:
A_trans = A.T
print(A_trans)

[[0 2 1]
 [1 0 2]
 [0 1 1]]
